### ISSUE TITLE
How to do the same but in a component ?

### ISSUE THREAD

**Issue by Apol0x** [Gigacore/react-weather-forecast#3]
Hi @Gigacore .
First of all, thanks to your repo.
I'm trying to the same, but in a component instead of a dashboard.
My questions is, How do you to get localization or open the pop-ups option that you give the option, to choose if you give your permission to get localization or not?. I'm a little bit lost 
Thanks

**Comment by Gigacore** [comment]
@Apol0x - I didn't quite catch your question. When you mean localization, are you referring to Geo-Location? The permission pop-ups are usually native to the browser.

**Comment by Apol0x** [comment]
@Gigacore Yes, that's right, Geo-Location.

**Comment by Gigacore** [comment]
@Apol0x - the browser will prompt user the first time he/she visits the application with it's native pop-up. Once allowed, it will continue to pick the geo-location automatically and will not re-prompt. If you have already allowed, you can try opening the application again in another browser or in the incognito window. Hope that answers.

<img width="651" alt="screen shot 2018-10-31 at 11 34 15 am" src="https://user-images.githubusercontent.com/278541/47769238-30e7bf00-dd01-11e8-81c2-69b176a773ab.png">

**Comment by Apol0x** [comment]
@Gigacore Fortunately I already got to understand why and how he asks for the permission to get the geo-location. Thank you
